#!/usr/bin/env bash
# crux-tools.sh — Helpful CRUX Linux administration menu

# ─── Colors ───────────────────────────────────────────────────────────────────
RESET='\033[0m'
BOLD='\033[1m'
DIM='\033[2m'
RED='\033[1;31m'
GREEN='\033[1;32m'
YELLOW='\033[1;33m'
BLUE='\033[1;34m'
CYAN='\033[1;36m'
WHITE='\033[1;37m'
MAGENTA='\033[1;35m'
BG_BLUE='\033[44m'

# ─── Helpers ──────────────────────────────────────────────────────────────────
HR() { printf "${DIM}${BLUE}%*s${RESET}\n" 70 '' | tr ' ' '─'; }
HEADER() {
    echo
    printf "${BG_BLUE}${WHITE}${BOLD}  %-66s  ${RESET}\n" "$1"
    HR
}
INFO()    { printf "  ${CYAN}●${RESET}  %s\n" "$1"; }
SUCCESS() { printf "  ${GREEN}✔${RESET}  %s\n" "$1"; }
WARN()    { printf "  ${YELLOW}⚠${RESET}  %s\n" "$1"; }
ERROR()   { printf "  ${RED}✘${RESET}  %s\n" "$1"; }
LABEL()   { printf "  ${YELLOW}${BOLD}%-28s${RESET} %s\n" "$1" "$2"; }

require_root() {
    if [[ $EUID -ne 0 ]]; then
        ERROR "This option must be run as root (use sudo or su)."
        return 1
    fi
}

press_enter() {
    echo
    printf "  ${DIM}Press [Enter] to return to the menu...${RESET}"
    read -r
}

# ─── Option 1 — pkgmk.conf: compiler flags + optimal defaults ─────────────────
opt_pkgmkconf() {
    HEADER "pkgmk.conf — Compiler Flags & Optimal Build Defaults"
    require_root || { press_enter; return; }

    local CONF="/etc/pkgmk.conf"

    if [[ ! -f "${CONF}" ]]; then
        ERROR "${CONF} not found. Is this a CRUX system?"
        press_enter; return
    fi

    local JOBS
    JOBS="$(nproc)"
    INFO "CPU cores detected : ${JOBS}"
    INFO "march=native will be used (optimise for this exact CPU)"

    # ── Backup ────────────────────────────────────────────────────────────────
    cp "${CONF}" "${CONF}.bak.$(date +%Y%m%d%H%M%S)" \
        && SUCCESS "Backup of ${CONF} created."

    # ── Idempotent update — export KEY="value" format used by pkgmk.conf ─────
    update_export() {
        local key="$1" value="$2" file="$3"
        # Match both  export KEY=  and  #export KEY=  (uncomment if needed)
        if grep -qE "^#?export ${key}=" "${file}" 2>/dev/null; then
            sed -i "s|^#\?export ${key}=.*|export ${key}=${value}|" "${file}"
        else
            echo "export ${key}=${value}" >> "${file}"
        fi
    }

    update_export 'CFLAGS'   '"-O2 -march=native -pipe"'           "${CONF}"
    update_export 'CXXFLAGS' '"$CFLAGS"'                            "${CONF}"
    update_export 'MAKEFLAGS' '"-j'"${JOBS}"' -l'"${JOBS}"'"'      "${CONF}"

    # Compression — zst is fastest; fall back to xz if zstd unavailable
    if command -v zstd &>/dev/null; then
        update_export 'PKGMK_COMPRESSION_MODE' '"zst"' "${CONF}"
        INFO "zstd found — setting PKGMK_COMPRESSION_MODE=zst (fastest)"
    else
        update_export 'PKGMK_COMPRESSION_MODE' '"xz"'  "${CONF}"
        INFO "zstd not found — using xz compression"
    fi

    # Keep source/package dirs tidy
    update_export 'PKGMK_CLEAN_SOURCES' '"no"'  "${CONF}"   # keep downloaded tarballs
    update_export 'PKGMK_KEEP_SOURCES'  '"yes"' "${CONF}"

    echo
    SUCCESS "pkgmk.conf updated.  Relevant lines:"
    HR
    grep -E '^export (CFLAGS|CXXFLAGS|MAKEFLAGS|PKGMK_)' "${CONF}" \
        | while IFS= read -r line; do
        printf "  ${GREEN}%s${RESET}\n" "${line}"
    done
    HR
    press_enter
}

# ─── Option 2 — Generate /etc/fstab ───────────────────────────────────────────
opt_fstab() {
    HEADER "Generate /etc/fstab with UUIDs & Optimal Options"
    require_root || { press_enter; return; }

    local FSTAB="/etc/fstab"
    cp -n "${FSTAB}" "${FSTAB}.bak.$(date +%Y%m%d%H%M%S)" 2>/dev/null \
        && SUCCESS "Existing fstab backed up."

    mount_opts() {
        local fs="$1" mp="$2"
        case "${fs}" in
            ext4)
                [[ "${mp}" == "/" ]] \
                    && echo "noatime,errors=remount-ro" \
                    || echo "defaults,noatime" ;;
            btrfs)
                echo "defaults,noatime,compress=zstd:1,space_cache=v2" ;;
            xfs)
                echo "defaults,noatime,largeio" ;;
            vfat|fat32|msdos)
                echo "defaults,noatime,fmask=0022,dmask=0022,codepage=437,iocharset=utf8,shortname=mixed" ;;
            swap)
                echo "sw" ;;
            tmpfs)
                echo "defaults,noatime,mode=0755" ;;
            *)
                echo "defaults,noatime" ;;
        esac
    }

    dump_pass() {
        local fs="$1" mp="$2"
        case "${fs}" in
            swap|tmpfs|vfat|fat32) echo "0 0" ;;
            *)
                [[ "${mp}" == "/" ]] && echo "0 1" || echo "0 2" ;;
        esac
    }

    {
        echo "# /etc/fstab — generated by crux-tools.sh on $(date)"
        echo "# <uuid/path>                                   <mp>     <type>   <options>                                         <dump> <pass>"
        echo

        while IFS= read -r line; do
            local dev mp fstype opts _rest
            read -r dev mp fstype opts _rest <<< "${line}"
            [[ "${dev}" == /dev/sd*    || "${dev}" == /dev/nvme* || \
               "${dev}" == /dev/vd*    || "${dev}" == /dev/hd*   || \
               "${dev}" == /dev/mmcblk* ]] || continue

            local uuid
            uuid="$(blkid -s UUID -o value "${dev}" 2>/dev/null)"
            [[ -z "${uuid}" ]] && { WARN "Could not get UUID for ${dev} — skipping." >&2; continue; }

            local chosen_opts dp
            chosen_opts="$(mount_opts "${fstype}" "${mp}")"
            dp="$(dump_pass "${fstype}" "${mp}")"

            printf "UUID=%-38s %-12s %-8s %-50s %s\n" \
                "${uuid}" "${mp}" "${fstype}" "${chosen_opts}" "${dp}"
        done < <(findmnt -rn -o SOURCE,TARGET,FSTYPE,OPTIONS --real)

        echo
        echo "# tmpfs"
        printf "%-42s %-12s %-8s %-50s %s\n" \
            "tmpfs" "/tmp" "tmpfs" "defaults,noatime,nosuid,nodev,size=2G,mode=1777" "0 0"

    } > "${FSTAB}"

    echo
    SUCCESS "New fstab written to ${FSTAB}:"
    HR
    while IFS= read -r l; do
        printf "  ${GREEN}%s${RESET}\n" "${l}"
    done < "${FSTAB}"
    HR
    WARN "Review carefully before rebooting.  Backup at ${FSTAB}.bak.*"
    press_enter
}

# ─── Option 3 — Full system upgrade & cleanup ─────────────────────────────────
opt_sysup() {
    HEADER "Full CRUX System Upgrade & Cleanup"
    require_root || { press_enter; return; }

    echo
    WARN "This will sync all port collections, upgrade the system, and check deps."
    printf "  ${YELLOW}${BOLD}Continue? [y/N]: ${RESET}"
    read -r confirm
    [[ "${confirm,,}" != "y" ]] && { INFO "Aborted."; press_enter; return; }

    # ── Verify required tools ─────────────────────────────────────────────────
    for cmd in ports prt-get pkgmk; do
        if ! command -v "${cmd}" &>/dev/null; then
            ERROR "Required command not found: ${cmd}  — is this a CRUX system?"
            press_enter; return
        fi
    done

    run_step() {
        local label="$1"; shift
        echo
        INFO "${label}"
        HR
        if ! "$@"; then
            WARN "${label} exited non-zero — check output above."
            printf "  ${YELLOW}Continue anyway? [y/N]: ${RESET}"
            read -r cont
            [[ "${cont,,}" != "y" ]] && { ERROR "Aborted."; return 1; }
        else
            SUCCESS "${label} done."
        fi
        return 0
    }

    # Step 1 — Sync all port collections defined in /etc/ports/*.conf
    run_step "Sync all port collections (ports -u)" \
        ports -u || { press_enter; return; }

    # Step 2 — Show available updates before applying
    echo
    INFO "Packages with available updates (prt-get diff):"
    HR
    prt-get diff 2>/dev/null | while IFS= read -r l; do
        printf "  ${CYAN}%s${RESET}\n" "${l}"
    done

    # Step 3 — Full system upgrade
    run_step "Upgrade all outdated packages (prt-get sysup)" \
        prt-get sysup || { press_enter; return; }

    # Step 4 — Rebuild packages with broken library dependencies
    if command -v revdep &>/dev/null; then
        echo
        INFO "Checking for broken reverse dependencies (revdep) ..."
        HR
        local broken
        broken="$(revdep 2>/dev/null)"
        if [[ -z "${broken}" ]]; then
            SUCCESS "No broken dependencies found."
        else
            WARN "Broken packages detected — rebuilding:"
            echo "${broken}" | while IFS= read -r pkg; do
                printf "  ${RED}  %s${RESET}\n" "${pkg}"
            done
            echo
            printf "  ${YELLOW}Rebuild broken packages now? [y/N]: ${RESET}"
            read -r rb
            if [[ "${rb,,}" == "y" ]]; then
                echo "${broken}" | xargs -r prt-get update -fr \
                    && SUCCESS "Broken packages rebuilt." \
                    || WARN "Some rebuilds failed — review output."
            fi
        fi
    else
        WARN "revdep not found (install prt-utils for reverse-dep checking)."
    fi

    # Step 5 — List orphaned packages (installed but not required by anything)
    echo
    INFO "Orphaned packages (prt-get listorphans) — installed but unrequired:"
    HR
    local orphans
    orphans="$(prt-get listorphans 2>/dev/null)"
    if [[ -n "${orphans}" ]]; then
        echo "${orphans}" | while IFS= read -r pkg; do
            printf "  ${YELLOW}  %s${RESET}\n" "${pkg}"
        done
        WARN "Review orphans above and remove manually with: prt-get remove <pkg>"
    else
        SUCCESS "No orphaned packages."
    fi

    # Step 6 — Show packages with footprint mismatches / missing files
    echo
    INFO "Checking package footprint integrity (pkginfo -i | spot-check)..."
    HR
    if command -v pkgcheck &>/dev/null; then
        pkgcheck 2>/dev/null | head -30 | while IFS= read -r l; do
            printf "  ${YELLOW}%s${RESET}\n" "${l}"
        done
    else
        INFO "pkgcheck not available — skipping footprint check."
    fi

    echo
    SUCCESS "System upgrade & cleanup sequence complete."
    press_enter
}

# ─── Option 4 — Bootloader info ───────────────────────────────────────────────
opt_bootloader() {
    HEADER "Bootloader & Boot Method Detection"

    if [[ -d /sys/firmware/efi ]]; then
        local boot_type="UEFI / EFI"
        local secboot
        if command -v mokutil &>/dev/null; then
            secboot="$(mokutil --sb-state 2>/dev/null || echo 'unknown')"
        else
            secboot="$(od -An -tx1 /sys/firmware/efi/efivars/SecureBoot-* 2>/dev/null \
                | awk 'NR==1{v=$(NF); print (v=="01") ? "enabled" : "disabled"}' \
                || echo 'unknown')"
        fi
        LABEL "Firmware:"    "${GREEN}${boot_type}${RESET}"
        LABEL "Secure Boot:" "${secboot}"

        local efi_part
        efi_part="$(findmnt -n -o SOURCE /boot/efi 2>/dev/null \
                    || findmnt -n -o SOURCE /efi   2>/dev/null \
                    || echo "not separately mounted")"
        LABEL "EFI partition:" "${efi_part}"
    else
        LABEL "Firmware:" "${YELLOW}Legacy BIOS / MBR${RESET}"
        local grub_disk
        grub_disk="$(lsblk -dpn -o NAME,TYPE | awk '$2=="disk"{print $1}' | head -1)"
        if [[ -n "${grub_disk}" ]]; then
            local mbr_sig
            mbr_sig="$(dd if="${grub_disk}" bs=512 count=1 2>/dev/null | strings)"
            if echo "${mbr_sig}" | grep -qi grub; then
                LABEL "MBR signature:" "GRUB detected on ${grub_disk}"
            elif echo "${mbr_sig}" | grep -qi lilo; then
                LABEL "MBR signature:" "LILO detected on ${grub_disk}"
            else
                LABEL "MBR check:" "No known bootloader signature in ${grub_disk}"
            fi
        fi
    fi

    echo
    HR

    # ── Detect installed bootloader binaries ──────────────────────────────────
    local detected=()
    { command -v grub-mkconfig &>/dev/null || command -v grub2-mkconfig &>/dev/null; } \
        && detected+=("GRUB 2")
    { command -v bootctl &>/dev/null && bootctl status &>/dev/null 2>&1; } \
        && detected+=("systemd-boot")
    command -v lilo      &>/dev/null && detected+=("LILO")
    command -v syslinux  &>/dev/null && detected+=("syslinux")
    command -v refind-install &>/dev/null && detected+=("rEFInd")

    if [[ ${#detected[@]} -gt 0 ]]; then
        LABEL "Detected bootloader(s):" "${detected[*]}"
    else
        WARN "No known bootloader command found in PATH."
    fi

    echo
    HEADER "Important Bootloader Files & Locations"

    # GRUB
    for f in \
        /boot/grub/grub.cfg  /boot/grub2/grub.cfg \
        /etc/default/grub    /etc/grub.d/          \
        /boot/grub/          /boot/efi/EFI/; do
        [[ -e "${f}" ]] && LABEL "GRUB:" "${f}"
    done

    # LILO (common on CRUX historically)
    for f in /etc/lilo.conf /boot/map; do
        [[ -e "${f}" ]] && LABEL "LILO:" "${f}"
    done

    # systemd-boot
    for f in \
        /boot/efi/loader/loader.conf  /efi/loader/loader.conf \
        /boot/loader/loader.conf      /boot/efi/loader/entries/ \
        /efi/loader/entries/; do
        [[ -e "${f}" ]] && LABEL "systemd-boot:" "${f}"
    done

    echo
    if [[ -d /sys/firmware/efi ]]; then
        INFO "EFI boot entries (efibootmgr):"
        HR
        if command -v efibootmgr &>/dev/null; then
            efibootmgr | while IFS= read -r l; do
                printf "    ${CYAN}%s${RESET}\n" "${l}"
            done
        else
            WARN "efibootmgr not installed (pkgmk it from opt or contrib ports)."
        fi
    fi

    press_enter
}

# ─── Option 5 — Kernel info ───────────────────────────────────────────────────
opt_kernel() {
    HEADER "Current Kernel & Important File Locations"

    LABEL "Running kernel:"  "$(uname -r)"
    LABEL "Architecture:"    "$(uname -m)"
    LABEL "Build date:"      "$(uname -v)"
    LABEL "Hostname:"        "$(uname -n)"

    echo
    HR
    INFO "Kernel image(s) in /boot:"
    find /boot -maxdepth 2 \
        \( -name "vmlinuz*" -o -name "kernel*" -o -name "bzImage*" \) 2>/dev/null \
        | sort | while IFS= read -r f; do
        LABEL "  kernel image:" "${f}  $(du -sh "${f}" 2>/dev/null | cut -f1)"
    done

    echo
    INFO "Initramfs image(s):"
    find /boot -maxdepth 2 \
        \( -name "initramfs*" -o -name "initrd*" \) 2>/dev/null \
        | sort | while IFS= read -r f; do
        LABEL "  initramfs:" "${f}  $(du -sh "${f}" 2>/dev/null | cut -f1)"
    done

    echo
    INFO "Kernel source trees in /usr/src:"
    if [[ -d /usr/src ]]; then
        local active_target sym
        active_target="$(readlink /usr/src/linux 2>/dev/null)"
        while IFS= read -r d; do
            sym=""
            [[ "${active_target}" == "${d}" || "${active_target}" == "/usr/src/${d}" ]] \
                && sym="${GREEN} ← active symlink${RESET}"
            printf "  ${CYAN}/usr/src/%-36s${RESET}%b\n" "${d}" "${sym}"
        done < <(ls /usr/src 2>/dev/null | grep -v '^$')
    else
        WARN "/usr/src not found."
    fi

    echo
    INFO "Active kernel config:"
    local kconfig=""
    for f in \
        "/usr/src/linux/.config" \
        "/proc/config.gz" \
        "/boot/config-$(uname -r)" \
        "/boot/config"; do
        if [[ -e "${f}" ]]; then kconfig="${f}"; break; fi
    done
    if [[ -n "${kconfig}" ]]; then
        LABEL "  .config:" "${kconfig}"
        if [[ "${kconfig}" == *.gz ]]; then
            INFO "  (compressed — use: zcat ${kconfig} | grep CONFIG_XXX)"
        fi
    else
        WARN "No kernel .config found in common locations."
    fi

    echo
    INFO "CRUX kernel build reminders:"
    HR
    printf "  ${DIM}  cd /usr/src/linux\n"
    printf "  make menuconfig          # configure\n"
    printf "  make -j$(nproc) && make modules_install\n"
    printf "  cp arch/x86/boot/bzImage /boot/vmlinuz\n"
    printf "  cp System.map /boot/System.map-\$(make kernelversion)\n"
    printf "  # then update /etc/lilo.conf or grub.cfg and re-run lilo/grub-mkconfig${RESET}\n"
    HR

    echo
    INFO "Other relevant paths:"
    LABEL "  Modules dir:"      "/lib/modules/$(uname -r)"
    LABEL "  Firmware dir:"     "/lib/firmware"
    LABEL "  CRUX ports dir:"   "/usr/ports/"
    LABEL "  Port collections:" "/etc/ports/"
    LABEL "  pkgmk.conf:"       "/etc/pkgmk.conf"
    LABEL "  prt-get.conf:"     "/etc/prt-get.conf"

    echo
    INFO "Loaded modules (top 20 by reference count):"
    HR
    lsmod 2>/dev/null | awk 'NR>1 {print $3, $1}' | sort -rn | head -20 \
        | while read -r sz mod; do
        printf "    ${CYAN}%-40s${RESET} ${DIM}%s refs${RESET}\n" "${mod}" "${sz}"
    done

    press_enter
}

# ─── Main menu ────────────────────────────────────────────────────────────────
print_menu() {
    clear
    echo
    printf "${BG_BLUE}${WHITE}${BOLD}%70s${RESET}\n" " "
    printf "${BG_BLUE}${WHITE}${BOLD}  %-66s  ${RESET}\n" "  ⚙  CRUX Linux Admin Toolkit"
    printf "${BG_BLUE}${WHITE}${BOLD}%70s${RESET}\n" " "
    HR
    echo
    printf "  ${GREEN}${BOLD}[1]${RESET}  ${WHITE}Configure pkgmk.conf${RESET}"
    printf "      ${DIM}— CFLAGS -march=native, MAKEFLAGS via nproc, compression${RESET}\n"

    printf "  ${GREEN}${BOLD}[2]${RESET}  ${WHITE}Generate /etc/fstab${RESET}"
    printf "         ${DIM}— UUIDs, optimal mount options per filesystem${RESET}\n"

    printf "  ${GREEN}${BOLD}[3]${RESET}  ${WHITE}Full system upgrade & cleanup${RESET}"
    printf "  ${DIM}— ports -u → prt-get sysup → revdep → orphans${RESET}\n"

    printf "  ${GREEN}${BOLD}[4]${RESET}  ${WHITE}Bootloader info${RESET}"
    printf "          ${DIM}— detect GRUB/LILO/EFI/BIOS, list key files${RESET}\n"

    printf "  ${GREEN}${BOLD}[5]${RESET}  ${WHITE}Kernel info${RESET}"
    printf "               ${DIM}— running kernel, sources, config, build hints${RESET}\n"

    echo
    printf "  ${RED}${BOLD}[0]${RESET}  ${WHITE}Exit${RESET}\n"
    echo
    HR
    printf "  ${YELLOW}${BOLD}Select an option: ${RESET}"
}

main() {
    while true; do
        print_menu
        read -r choice
        case "${choice}" in
            1) opt_pkgmkconf ;;
            2) opt_fstab     ;;
            3) opt_sysup     ;;
            4) opt_bootloader;;
            5) opt_kernel    ;;
            0|q|Q|exit)
                echo
                printf "  ${GREEN}Goodbye.${RESET}\n\n"
                exit 0
                ;;
            *)
                echo
                WARN "Unknown option '${choice}' — please choose 0–5."
                sleep 1
                ;;
        esac
    done
}

main "$@"
